version: 0.1
scenario_id: tier1_dso_SCHEDULING_NO_SHOWS
name: Scheduling – Reduce No-Shows
agent_name: Scheduling Agent
tags: [dso, scheduling, reminders, no-shows]
triggers: >
  Regional dental groups operate 5–15 clinics… High no-show rates (15–20%) cause lost chair time and staff frustration.
best_reply_shapes: [email]
risk_notes: >
  HIPAA/PHI; TCPA consent logging; quiet hours 21:00–08:00.
how_it_works: >
  Connect PMS; monitor schedule; send reminders; auto-confirm; cancellations trigger prioritized waitlist fill; staff sees the final confirmed schedule.
tool_stack_dev: >
  PMS API + n8n; Email for demo; Google Sheets for waitlist; optional Slack daily summary.
roi_hypothesis: >
  Reduce no-shows from ~18% → ~10% within 6 weeks; recover 6–10 hrs chair time/clinic/week.
connectors:
  pms: [dentrix, eaglesoft, opendental]
  comms: [email, slack, gcal]
entities: [patient, appointment, waitlist_entry]
intents: [confirm, cancel, reschedule, late, human]
